fix workflow

diff --git a/.github/workflows/gitops.yaml b/.github/workflows/gitops.yaml
--- a/.github/workflows/gitops.yaml
+++ b/.github/workflows/gitops.yaml
@@ -14,100 +14,90 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3  # Проверяем репозиторий
 
-      - name: "Step test"
+      - name: Set up Node.js 20
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+
+      - name: Install dependencies
+        run: npm ci  # Быстрая установка зависимостей
+
+      - name: Build frontend
+        run: npm run build  # Сборка проекта
+
+      # - name: Check if branch is `main` and if it's approved
+      #   if: github.ref == 'refs/heads/main' && github.event.pull_request.review.state == 'approved'
+      #   run: echo "This is the main branch, proceeding only after approval"
+
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: Build and push Docker image for frontend
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile  # Указываем путь к Dockerfile
+          push: true
+          build-args: |
+            TARGET_ENV=${{ env.BRANCH_NAME }}
+          tags: |
+            invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}
+            invariant0x/fightclub-frontend:latest
+
+      - name: Checkout deployment repository
+        uses: actions/checkout@v4
+        with:
+          repository: Invariant0x/FightClubApp-DevOps  # Репозиторий для деплоя
+          token: ${{ secrets.FC_ACTION_PRIVATE_TOKEN }}
+
+      - name: TEST Update WEB-deployment.yaml with new Docker image
         if: ${{ env.BRANCH_NAME == 'test' }}
-        run: echo "Test step echo"
+        run: |
+          cd fc-dev/applications/frontend
+          echo "Current directory: $(pwd)"
+          ls -la
+          sed -i 's|image: invariant0x/fightclub-frontend:.*|image: invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}|g' WEB-deployment.yaml
+          git config --global user.name "Invariant get action"
+          git config --global user.email "invariant0x@icloud.com"
+          git add WEB-deployment.yaml
+          git commit -m "TEST Update WEB-deployment.yaml with new Docker image"
+          git push origin HEAD:main
 
-      - name: "Step main"
+      - name: PROD Update WEB-deployment.yaml with new Docker image
         if: ${{ env.BRANCH_NAME == 'main' }}
-        run: echo "Main step echo"
+        run: |
+          cd fc-prod/applications/frontend
+          echo "Current directory: $(pwd)"
+          ls -la
+          sed -i 's|image: invariant0x/fightclub-frontend:.*|image: invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}|g' WEB-deployment.yaml
+          git config --global user.name "Invariant get action"
+          git config --global user.email "invariant0x@icloud.com"
+          git add WEB-deployment.yaml
+          git commit -m "PROD Update WEB-deployment.yaml with new Docker image"
+          git push origin HEAD:main
 
-    # steps:
-    #   - name: Checkout repository
-    #     uses: actions/checkout@v3  # Проверяем репозиторий
+      - name: Remove old Docker images
+        run: |
+          # Получаем JWT токен
+          token=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
 
-    #   - name: Set up Node.js 20
-    #     uses: actions/setup-node@v3
-    #     with:
-    #       node-version: '20'
+          # Получаем список тегов
+          response=$(curl -s -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/fightclub-frontend/tags?page_size=100")
+          echo "Response: $response"
 
-    #   - name: Install dependencies
-    #     run: npm ci  # Быстрая установка зависимостей
+          # Проверяем, что ответ не пустой и содержит результаты
+          tags=$(echo $response | jq -r '.results | sort_by(.last_updated)')
+          if [ "$tags" == "null" ]; then
+            echo "No tags found or failed to fetch tags."
+            exit 1
+          fi
 
-    #   - name: Build frontend
-    #     run: npm run build  # Сборка проекта
-
-    #   # - name: Check if branch is `main` and if it's approved
-    #   #   if: github.ref == 'refs/heads/main' && github.event.pull_request.review.state == 'approved'
-    #   #   run: echo "This is the main branch, proceeding only after approval"
-
-    #   - name: Log in to Docker Hub
-    #     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-
-    #   - name: Build and push Docker image for frontend
-    #     uses: docker/build-push-action@v5
-    #     with:
-    #       context: .
-    #       file: ./Dockerfile  # Указываем путь к Dockerfile
-    #       push: true
-    #       build-args: |
-    #         TARGET_ENV=${{ env.BRANCH_NAME }}
-    #       tags: |
-    #         invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}
-    #         invariant0x/fightclub-frontend:latest
-
-    #   - name: Checkout deployment repository
-    #     uses: actions/checkout@v4
-    #     with:
-    #       repository: Invariant0x/FightClubApp-DevOps  # Репозиторий для деплоя
-    #       token: ${{ secrets.FC_ACTION_PRIVATE_TOKEN }}
-
-    #   - name: TEST Update WEB-deployment.yaml with new Docker image
-    #     if: ${{ env.BRANCH_NAME == 'test' }}
-    #     run: |
-    #       cd fc-dev/applications/frontend
-    #       echo "Current directory: $(pwd)"
-    #       ls -la
-    #       sed -i 's|image: invariant0x/fightclub-frontend:.*|image: invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}|g' WEB-deployment.yaml
-    #       git config --global user.name "Invariant get action"
-    #       git config --global user.email "invariant0x@icloud.com"
-    #       git add WEB-deployment.yaml
-    #       git commit -m "TEST Update WEB-deployment.yaml with new Docker image"
-    #       git push origin HEAD:main
-
-    #   - name: PROD Update WEB-deployment.yaml with new Docker image
-    #     if: ${{ env.BRANCH_NAME == 'main' }}
-    #     run: |
-    #       cd fc-prod/applications/frontend
-    #       echo "Current directory: $(pwd)"
-    #       ls -la
-    #       sed -i 's|image: invariant0x/fightclub-frontend:.*|image: invariant0x/fightclub-frontend:${{ env.BRANCH_NAME }}-${{ github.sha }}|g' WEB-deployment.yaml
-    #       git config --global user.name "Invariant get action"
-    #       git config --global user.email "invariant0x@icloud.com"
-    #       git add WEB-deployment.yaml
-    #       git commit -m "PROD Update WEB-deployment.yaml with new Docker image"
-    #       git push origin HEAD:main
-
-    #   - name: Remove old Docker images
-    #     run: |
-    #       # Получаем JWT токен
-    #       token=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
-
-    #       # Получаем список тегов
-    #       response=$(curl -s -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/fightclub-frontend/tags?page_size=100")
-    #       echo "Response: $response"
-
-    #       # Проверяем, что ответ не пустой и содержит результаты
-    #       tags=$(echo $response | jq -r '.results | sort_by(.last_updated)')
-    #       if [ "$tags" == "null" ]; then
-    #         echo "No tags found or failed to fetch tags."
-    #         exit 1
-    #       fi
-
-    #       # Удаляем все теги, кроме последних 10
-    #       images=$(echo $tags | jq -r '.[0:-10] | .[].name')
-    #       for image in $images; do
-    #         echo "Deleting image: $image"
-    #         curl -s -X DELETE -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/fightclub-frontend/tags/$image/"
-    #       done
+          # Удаляем все теги, кроме последних 10
+          images=$(echo $tags | jq -r '.[0:-10] | .[].name')
+          for image in $images; do
+            echo "Deleting image: $image"
+            curl -s -X DELETE -H "Authorization: JWT $token" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/fightclub-frontend/tags/$image/"
+          done
